### ISSUE TITLE
Create a link^2 to go to the data dictionary and add text

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWebTool#113]
Create a link^2 to go to the data dictionary and add - learn more about the variables `[here](link-to-dictionary)` and on the methodology here[link to methodology tab]. We also welcome `[feedback](link to a Google Form for feedback)`^3

**Comment by Tilmon** [comment]
Hi @AnneSchoenauer and @maurolepore , 

re

> And which is the link to the feedback form?
@Tilmon will create the link. @Tilmon once you created the feedback form could you share the link?

here is the [link to the feedback form](https://docs.google.com/forms/d/1cwPCtlW3xP97aNIZ9Isge2zw5nJ-JnXvteckCO4oawo/edit): Just finished it on Friday and wanted to share it in a separate ticket today. But now I'll just share it here :) 

Or @maurolepore do you prefer me to document the link somewhere else?

**Comment by maurolepore** [comment]
Thanks! Here is fine. I'll ask more questions when we make this my priority. But it's great to collect all the relevant information here.

**Comment by maurolepore** [comment]
What's suggested here is surely possible and I'm happy to do it so you can see what it looks and feels like. 

I'm no expert in design, but did read the classic "The design of everyday things" and I recall reading that the easiest to use tools are those where each control maps to a single function. Here the "control" would be a "tab", and the functions would be these:

1. Select and view the data they want to explore.
2. Request the data.
3. Learn about the license of the data.
4. Access the dictionary.
5. Access the feedback form.
6. Access the methodology.

I agree that these 6 functions are important but it seems like the app would be more user friendly if each function has its dedicated control.

The image below shows the app-sections more completely, including an expanded view of what's under the dropdown "More".

![Image](https://github.com/user-attachments/assets/dce46f0e-b17a-4edb-bf11-6ab290cfa0bd)

Users land on "Disclaimer", next they're encouraged to click on "Welcome", and then they will most likely go to "Dataset" -- since it's the main goal they try to achieve (use data).  This gives the user the change to "learn" how to navigate the app. It seems unlikely they'll miss the next tab "Dictionary", so a link to it from the "Dataset" tab seems to add little extra value.

Of course, the only real way to know is to run some usability tests, where we watch naive user and see what they actualy do.

The items 2., 3., 5. and 6. have something in common: They are just links to external resources. In many websites that's handled via strategically placed icons -- often on the navigation bar (e.g. https://www.flaticon.com/free-icons/common). Another option might be to place them under "More".

**Comment by AnneSchoenauer** [comment]
Hi @Tilmon, If it is something that is hard to implement than it is really just an enhancement. I gave Sönke the webtool and asked him for feedback and that was one of his feedback that he didn't understand the variables and that some explanations would be nice to have. He wanted to have a funciton where you have a question mark for each variable and if you touch the question mark a text box appears with explanations. As this might be an overkill to implement I thought it would be nice to have a hyperlink to the "More" section where the methodology is based. So the idea was not to put the methodology document and the dictionary on one page BUT to have hyperlinks taht are then linking to the pages for the More and data dictionary section. Similiar to the "request data" under CC BY - NC-ND 4.0 that you see in the screenshot. They are also hyperlinks in green. Would be nice to add a sentence with if you want to see the data dictionary click here (hyperlink) or the methodology data to understand better the variables (here). I still think that this would be a good idea. What do you think @Tilmon?

**Comment by Tilmon** [comment]
Hi @AnneSchoenauer and @maurolepore ok, didn't know that is already based on first-hand user feedback :) Then that's completely fine for me if @maurolepore still has time for this!
