### ISSUE TITLE
Define dictionary columns

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWebTool#12]
* [Sheet](https://docs.google.com/spreadsheets/d/1gOZRS9_0yUgR7UXgsf4WmDoAEXfUQy3Mz0MZM1Xvv40/edit?gid=422716179#gid=422716179)
* [Instructions to update the dictionary](https://github.com/2DegreesInvesting/tiltWebTool/pull/184#discussion_r1710326507)
-----
* Relates to https://github.com/2DegreesInvesting/tiltWebTool/issues/139
* Follows up #11 
* May reuse [this googlesheet ](https://docs.google.com/spreadsheets/d/1SpeZZJOvs3Kz1uYfeGLQtwdARVntkaPX/edit#gid=1097155358) -- the latest version of data dictionary from the logical data model. It may be outdated and focused on inputs (not outputs).

--

> If you would like to assign me this task then please create a separate ticket for me and adjust the priority of this task on my board! Thanks! :) -- @kalashsinghal in https://github.com/2DegreesInvesting/tiltWebTool/issues/11#issuecomment-2133632701

@kalashsinghal, this is the ticket, and the attached .csv files were generated as you say -- "[from profile_emissions and profile_sector functions of tiltIndicatorAfter](https://github.com/2DegreesInvesting/tiltWebTool/issues/11#issuecomment-2133632701)".

* [tiltIndicatorAfter-v0.0.0.9040-emissions.csv](https://github.com/2DegreesInvesting/tiltWebTool/files/15440608/tiltIndicatorAfter-v0.0.0.9040-emissions.csv)
* [tiltIndicatorAfter-v0.0.0.9040-sector.csv](https://github.com/2DegreesInvesting/tiltWebTool/files/15440736/tiltIndicatorAfter-v0.0.0.9040-sector.csv)

<details>
<summary>
reprex
</summary>

## Emissions

``` r
sector <- readr::read_csv("tiltIndicatorAfter-v0.0.0.9040-emissions.csv")
#> Rows: 42 Columns: 5
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr (4): dataset, level, name, type
#> lgl (1): definition
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
```

``` r

head(sector)
#> # A tibble: 6 × 5
#>   dataset   level   name             type      definition
#>   <chr>     <chr>   <chr>            <chr>     <lgl>     
#> 1 emissions product companies_id     character NA        
#> 2 emissions product company_name     character NA        
#> 3 emissions product country          character NA        
#> 4 emissions product emission_profile character NA        
#> 5 emissions product benchmark        character NA        
#> 6 emissions product ep_product       character NA
```

``` r

tail(sector)
#> # A tibble: 6 × 5
#>   dataset   level   name                type      definition
#>   <chr>     <chr>   <chr>               <chr>     <lgl>     
#> 1 emissions company company_city        character NA        
#> 2 emissions company postcode            character NA        
#> 3 emissions company address             character NA        
#> 4 emissions company main_activity       character NA        
#> 5 emissions company profile_ranking_avg double    NA        
#> 6 emissions company co2_avg             double    NA
```

## Sector

``` r
sector <- readr::read_csv("tiltIndicatorAfter-v0.0.0.9040-sector.csv")
#> Rows: 39 Columns: 5
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr (4): dataset, level, name, type
#> lgl (1): definition
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
```

``` r

head(sector)
#> # A tibble: 6 × 5
#>   dataset level   name              type      definition
#>   <chr>   <chr>   <chr>             <chr>     <lgl>     
#> 1 sector  product companies_id      character NA        
#> 2 sector  product company_name      character NA        
#> 3 sector  product country           character NA        
#> 4 sector  product sector_profile    character NA        
#> 5 sector  product reduction_targets double    NA        
#> 6 sector  product scenario          character NA
```

``` r

tail(sector)
#> # A tibble: 6 × 5
#>   dataset level   name                               type      definition
#>   <chr>   <chr>   <chr>                              <chr>     <lgl>     
#> 1 sector  company matching_certainty_company_average character NA        
#> 2 sector  company company_city                       character NA        
#> 3 sector  company postcode                           character NA        
#> 4 sector  company address                            character NA        
#> 5 sector  company main_activity                      character NA        
#> 6 sector  company reduction_targets_avg              double    NA
```

</details>

<details>

Here is how I did it. The trick is to use [this helper](https://2degreesinvesting.github.io/tiltDevTools/reference/extensions.html).

## Emissions

```r
library(readr, warn.conflicts = FALSE)
library(tiltToyData)
library(tiltIndicatorAfter)
library(tiltDevTools)

companies <- read_csv(toy_emissions_profile_any_companies())
products <- read_csv(toy_emissions_profile_products_ecoinvent())
europages_companies <- read_csv(toy_europages_companies())
ecoinvent_activities <- read_csv(toy_ecoinvent_activities())
ecoinvent_europages <- read_csv(toy_ecoinvent_europages())
isic_name <- read_csv(toy_isic_name())

emissions <- profile_emissions(
  companies,
  products,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_europages = ecoinvent_europages,
  isic = isic_name
)

version <- packageVersion("tiltIndicatorAfter")

emissions |> 
  use_dictionary() |> 
  write_csv(glue::glue("tiltIndicatorAfter-v{version}-emissions.csv"))
```

## Sector

```r
library(readr, warn.conflicts = FALSE)
library(tiltToyData)
library(tiltIndicatorAfter)
library(tiltDevTools)

companies <- read_csv(toy_sector_profile_companies())
scenarios <- read_csv(toy_sector_profile_any_scenarios())
europages_companies <- read_csv(toy_europages_companies()) |> head(3)
ecoinvent_activities <- read_csv(toy_ecoinvent_activities()) |> head(3)
ecoinvent_europages <- read_csv(toy_ecoinvent_europages()) |> head(3)
isic_name <- read_csv(toy_isic_name()) |> head(3)

sector <- profile_sector(
  companies,
  scenarios,
  europages_companies = europages_companies,
  ecoinvent_activities = ecoinvent_activities,
  ecoinvent_europages = ecoinvent_europages,
  isic = isic_name
)

version <- packageVersion("tiltIndicatorAfter")

sector |> 
  use_dictionary() |> 
  write_csv(glue::glue("tiltIndicatorAfter-v{version}-sector.csv"))

```

</details>

**Comment by Tilmon** [comment]
Hi @kalashsinghal thanks for your support here. Let's prioritize tomorrow in the sprint. I'm also still waiting for response from Yana, who (I believe) has worked on something similar in the past. Maybe we can use that as input.

**Comment by Tilmon** [comment]
Addendum: Here is a Wikipedia [ article about data dictionaries](https://en.wikipedia.org/wiki/Data_dictionary). It lists out possible data attributes that are listed in such dictionairies. I think Mauro's template already captures the most relevant ones, but probably good to think about whether we think additional columns could be useful.

**Comment by Tilmon** [comment]
@maurolepore please see this comment for the data dictionary from the DT, just for reference: https://github.com/2DegreesInvesting/tiltWebTool/issues/12#issuecomment-2133975210

I'll work on it next week.

**Comment by Tilmon** [comment]
Dear @maurolepore , 

I created a separate tab with the data dictionary, based on all columns that are in the webtool data: [https://docs.google.com/spreadsheets/d/1gOZRS9_0yUgR7UXgsf4WmDoAEXfUQy3Mz0MZM1Xvv40/edit?gid=422716179#gid=422716179](https://docs.google.com/spreadsheets/d/1gOZRS9_0yUgR7UXgsf4WmDoAEXfUQy3Mz0MZM1Xvv40/edit?gid=422716179#gid=422716179)

@maurolepore I didn't fill in the column 'dataset' because I didn't know if this still applies now that we have all data in one table? I assume we don't need that column then anymore, but I might be wrogn. 

@AnneSchoenauer and @kalashsinghal can you please review it? 

@AnneSchoenauer when creating the data dicitonary, I realized that we didn't include the column `grouping_sector` into the list of columns for the webtool. We have `year` and `scenario` in there, which is the grouping, but no separate ``grouping_sector` column. Do you remember if that was on purpose? I included it now in the dictionary just in case we add it. It would probably be nice to have it in there, just for consistency, but also not required, as the information is already captured in `year` and `scenario`. 
I'll leave it up to you and @kalashsinghal to decide next week whether you still want to include that column.

**Comment by maurolepore** [comment]
Thanks @Tilmon 
I think you're right, the "dataset" column may no longer apply.

**Comment by maurolepore** [comment]
* Thanks! I'll close it as done and follow up in #181

**Comment by Tilmon** [comment]
Hi @maurolepore there is one last question in the data dictionary sheet for you. After resolving that, I think we can close this ticket :) 

cc' @AnneSchoenauer

**Comment by maurolepore** [comment]
It seems this is done. If not feel free to reopen. I'm trying to prune remaining issues to we can more clearly see what's missing and we don't forget important stuff.
