### ISSUE TITLE
Prove that we can handle data of a realistically large size

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWebTool#121]
* Relates to #96 
* Relates to #125 

It seems the total sized of our data could fit in the free tier of Google Storage (gcs, #125), a GitHub release, and even GitHub commits -- if we partition parquet files small enough. 

The issue to solve is then latency. If the data is remote to the app, then the queries travel through the network. We can cache the requested data but then we may as well store the data along with the app. 

If we store the data with the app, we solve latency for the user but slow down deployment. To solve this we may architect the Docker image that contains the app in such a way that the data is added at a point that benefits from Docker's ability to reuse cached layers -- i.e. so that layers that change frequently are placed towards the end. 

- [x] Study gcs to Confirm the size limit for the free tier of gcs. (4GB in total for the service)
- [x] Research the cost of a managed database for comparison. (~$15-50/month)
- [x] Test if duckdbfs can read files from a GitHub repository. (It can but reading through the network is slower)
- [x] Test if the database can be hosted as .parquet in Google Storage and read into the app. (Yes but reading from gcs is slower and we need to pay for the gcs bucket).
- [x] Compare duckdb, arrow, and maybe other options. (arrow seems best. Duckdb takes forever to install)
- [x] Test if the database copied into the same container that runs the app. (Yes, see architecture below)

**Comment by maurolepore** [comment]
This reprex shows we can read a parquet dataset as a duckdb database.

``` r
library(duckdb)
#> Loading required package: DBI
library(dplyr)

from <- function(parent) {
  sprintf("read_parquet('%s/**/*.parquet', hive_partitioning = true)", parent)
}

parent <- "../tiltWebtoolData/inst/extdata/company"
fs::dir_tree(parent)
#> ../tiltWebtoolData/inst/extdata/company
#> ├── country=fake1
#> │   └── data_0.parquet
#> ├── country=fake2
#> │   └── data_0.parquet
#> └── country=fake3
#>     └── data_0.parquet

con <- dbConnect(duckdb::duckdb(), dbdir = ":memory:")

tbl(con, from = from(parent)) |>
  filter(grepl("mauro", companies_id)) |>
  distinct(companies_id)
#> # Source:   SQL [4 x 1]
#> # Database: DuckDB v1.0.0 [unknown@Linux 6.5.0-41-generic:R 4.4.0/:memory:]
#>   companies_id                                                   
#>   <chr>                                                          
#> 1 mauro-transportsysteme-gmbh_00000005069812-001                 
#> 2 mauro-automotive_00000004833407-001                            
#> 3 kanzlei-dott-fabrizio-ricci-dott-mauro-ricci_00000005129626-001
#> 4 marcello-mauro-metallbau_deu113129-00101
```

<sup>Created on 2024-07-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by maurolepore** [comment]
On Google Cloud Run the image must be 4GB or less. It seems we may be able to fit all the data and software. This means we may be able to just pay as little as possible and experience minimum latency. 

### Data inside the app ~ $15/month

The architecture that seems most promising right now is this:

* app/: Public repo for the UI and tiny toy data/
* appAndData/: Private repo with real data/. It depends on app/ and can start from a Docker image that already has app/ installed.
* Total estimated cost for 5 users daily (1h each): $15/month

ChatGTP estimated the cost assuming 5 users, each using it for  1h everyday.

### Data on Google Cloud Storage ~ $35/month

A more scalable alternative is to move the data to a Google Cloud Storage Bucket and moount it into the app's container.

ChatGTP estimated the cost assuming 5 users, each using it for  1h everyday.

**Comment by maurolepore** [comment]
One big caveat is that the container seems to take forever to build and it seems the be caused by building duckdb. Can we speed things up with arrow or nanoparquet?

**Comment by Tilmon** [comment]
Dear @maurolepore, "The best option" (https://github.com/2DegreesInvesting/tiltWebTool/issues/121#issuecomment-2226582306) for 15€/months sounds good :) Please go ahead with that one. Just aligned on it with @AnneSchoenauer .
