### ISSUE TITLE
Create large sample dataset to test webtool

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltWebTool#125]
Hi @maurolepore, 

to test functionality of the Webtool, you need a large dataset that's close to the real & final one. Therefore, how about you use the Budnesbank Output that's been already generated and "just" duplicate all rows to increase the size of the data? Afaik, the main purpose is to see how it operates with large files, hence "wrong" data shouldn't be a problem. 

You can find the latest version of the Bundesbank data [here](https://drive.google.com/drive/folders/1Js0oLDFHFNHLrtoZum97CzJyHZy6vG_T). Please note this data only covers 1/3 of all companies. Hence, the data used in the webtool will be approximately 3 times as large.

**Comment by maurolepore** [comment]
Thanks @Tilmon 

I see these files add up to a total size of ~80MB, so 80 x 3 = 240MB for Germany alone, right? So maybe 3 times that for all five countries -- to a total guess of about 750MB.

That seem not-too bad. There is a good chance that we can host that for free on Google Storage.

But please let me know if my interpretation of the total expected size is wrong.

**Comment by maurolepore** [comment]
In any case, those files should be useful to work on the issue where I need them:

* #121

**Comment by Tilmon** [comment]
@maurolepore 

> I see these files add up to a total size of ~80MB, so 80 x 3 = 240MB for Germany alone, right? So maybe 3 times that for all five countries -- to a total guess of about 750MB.

The files already contain all data for GER. I.e., the size of 80 MB for the zipped files is for whole GER, hence it would only be 80 x 3 = 240 MB for all five countries - so even less of a problem then :)
