### ISSUE TITLE
Study authentication more deeply

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWebTool#14]
Tasklist

- [ ] Study and explain [how to authorize users on shinyapps.io](https://docs.posit.co/shinyapps.io/guide/index.html)
- [ ] Study how easy/hard it would be to implement shinyproxy authentication with GH copilot.
- [ ] Study what's involved in purchasing services that include authentication. Compare shinyapps.io and positconnect.
- [ ] Study if we need to create an account for shinyapps.io/positconnect for tiltSMEs

Custom authentication page

- [ ] Study if the autentication page can be customized for colours/brand.
- [ ] Study if the autentication page can be customized to add agreement that the usage is only for research

Can I change the authentication page of shinyapps.io to match my company's branding?

> shinyapps.io does not allow direct modification of the login page as it is managed by the platform.
> If you're leveraging shinyapps.io's built-in authentication, your customization options might be limited to what can be done within the Shiny app itself, without directly modifying the shinyapps.io login page.
> If you need more advanced customization, you might consider deploying your Shiny app on a custom server where you have full control over the authentication mechanism and the login page design.

I see Apsilon hacked a solution in Posit connect (similar to shinyapps.io) but it seems to require a lot of work: https://www.appsilon.com/post/custom-login-page-for-rstudio-connect
Consider contacting them to ask for a quote: https://www.appsilon.com/

I see Posit connect allows for some customization of the landing page: https://docs.posit.co/connect/1.8.4/admin/appendix/custom-landing/

**Comment by AnneSchoenauer** [comment]
@Tilmon I think this has a high priority. As this is a must-have. The reason why it is a must-have is that we need the use to accept our 'Terms of references' to only use the data for research purposes. Let's discuss in the tech-sprint

**Comment by maurolepore** [comment]
* Replace by #83
