### ISSUE TITLE
Show the updated dictionary

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWebTool#181]
* Relates to https://github.com/2DegreesInvesting/tiltWebTool/issues/12#issuecomment-2252661627

[Sheet](https://docs.google.com/spreadsheets/d/1gOZRS9_0yUgR7UXgsf4WmDoAEXfUQy3Mz0MZM1Xvv40/edit?gid=422716179#gid=422716179)

**Comment by AnneSchoenauer** [comment]
@maurolepore please note that @Tilmon still needs to review my comments when he is back from his holiday - however, as I understood you, it is also good if we learn how to update the XLS sheet on our own so maybe also good exercise that we update the XLS sheet when you are away.

**Comment by maurolepore** [comment]
My approach is to expose in the app whatever the googlesheet contains. So you update it the as usual and the app should automatically reflect your update the next time it's built (which happens automatically when I push any code change to GitHub. 

* So yeah, the issue that needs your input is: https://github.com/2DegreesInvesting/tiltWebTool/issues/12 


I'll reopen it for you to remember.
