### ISSUE TITLE
Make font-size bigger

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltWebTool#182]
* Relates to https://github.com/2DegreesInvesting/tiltWebTool/issues/119#issuecomment-2214836418

> **font_scale**  
> A scalar multiplier to apply to the base font size. For example, a value of 1.5 scales font sizes to 150% and a value of 0.8 scales to 80%. Must be a positive number.

https://rstudio.github.io/bslib/reference/bs_theme.html#arguments

**Comment by AnneSchoenauer** [comment]
Dear @maurolepore it would be great if the font size could be bigger as it is very small. I am happy to play around again if you give me the customisable app. Otherwise you could just tell me what font size you are using right now and we try two-four bigger sizes.

**Comment by maurolepore** [comment]
@AnneSchoenauer as I explain in the comment linked above, what we can adjust easily is the parameter `font_scale`.

The parameter `font_scale` seems to affect only the test -- NOT the headings, icons, etc. So it you want to change the relationship between the text and everything else, the easiest way is to actually reduce the size of the text and increase the zoom level.

AFAIK, other ways of adjusting the relationship between the text and headings/icons/etc. involve modifying the guts of the theme -- which may be easy for someone with experience in css or javascript or other web-technologies. For me it's one of those unkonwns that can be a rabbit hole and take way more time than seems worth it.

## Compare

* Browser zoom 100%, `font_scale = 1`

![Image](https://github.com/user-attachments/assets/4cda2727-4f5b-46f3-a1d0-02a365e01ed4)

* Browser zoom 100%, `font_scale = 1.5`

![Image](https://github.com/user-attachments/assets/b7a68ee7-08ba-4331-a86d-45b7c09f3ee5)

* Browser zoom 100%, `font_scale = 0.5`

![Image](https://github.com/user-attachments/assets/5494e1ef-e44d-4848-aba5-93a795f25bc6)

* Browser zoom 200%, `font_scale = 0.5`

![Image](https://github.com/user-attachments/assets/87b3ff0b-8398-49c4-b675-a0c171cec41c)

**Comment by AnneSchoenauer** [comment]
Hi @maurolepore thanks for your explanation and the picture. I would like to go with browser 100% and font_scale = 1.5. thanks!
