### ISSUE TITLE
Uploading a PDF document that can be downloaded from users

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltWebTool#197]
Dear @maurolepore, I added a [link to the](https://docs.google.com/document/d/14syERZ-t1nzZaiotL77zcvKVqoJ_47NA/edit) methodology document for a pull request. However, I was wondering if we could also upload a PDF file that user could download. The reason is that the Google Links sometimes make formatting etc of documents different. If this is a big problem and need a lot of effort, we can also leave it as it is. If it is something implemented pretty easily it would be great to explore this option. 
Best
Anne

**Comment by maurolepore** [comment]
@AnneSchoenauer 

* Can you open the file for me? Maybe to mauro@2degrees-investing.org?
* Does the PDF need to be private or can it be hosted somewhere publicly? If the PDF is public, then it's easy to allow users to download it via a link in the app.

**Comment by AnneSchoenauer** [comment]
@maurolepore 
ml01: I opened the file to you
ml02: the URL of the PDF can be open - so no need to be private! Great to know that a pdf would work :)

**Comment by maurolepore** [comment]
Thanks. 

So you can see what it would look like to Publish to web [here is a published version available only to memebers of 2degrees-investing.org](https://docs.google.com/document/d/14syERZ-t1nzZaiotL77zcvKVqoJ_47NA/pub). 

As mentioned above, this might look a lil different than  a .pdf but has the great advantage of updating automatically.

**Comment by AnneSchoenauer** [comment]
@maurolepore - and could we do a pdf as well? So if we don’t want to update it? Just as a question - no need to implement it now!

**Comment by maurolepore** [comment]
@AnneSchoenauer, yes, you can print a PDF and drag it into a GitHub issue-comment like I do here. GitHub will automatically generate something like this:

```
[pdf-test.pdf](https://github.com/user-attachments/files/16681806/pdf-test.pdf)
```

[pdf-test.pdf](https://github.com/user-attachments/files/16681806/pdf-test.pdf)

So you can get the URL and use it with a custom phrase on the app, e.g.:

```
[Download this .pdf](https://github.com/user-attachments/files/16681806/pdf-test.pdf)
```

[Download this .pdf](https://github.com/user-attachments/files/16681806/pdf-test.pdf)
