### ISSUE TITLE
Change text for the 'welcoming page'

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltWebTool#203]
Update: [doc](https://docs.google.com/document/d/1dn29mtGD1fbtY1jIvLUVvZZX1KC3IHX7vNjpLEU20E8/edit) ([slack](https://2investinginitiative.slack.com/archives/C07BVEXP272/p1724178242773639)).

---

Dear @maurolepore, 

I am not quite sure how to do it as I said earlier. I would like to have sub-headings at the welcoming page and I think this made the pull request blocked as I missinterpreted it how it goes. I am copying in here the text and it would be fantastic if you could implement it. If it is not working with the subheadings could you then make paragraphs and then some text in bold so that it looks like subheadings?

WELCOMING PAGE

**Welcome to tilt's Online Portal** [heading]

Our mission is to empower Small and Medium Enterprises (SMEs) across the EU and beyond with the funding and expertise needed to thrive in a net-zero future by 2050.

_tilt_  (Transforming in a Low Carbon Transition) is our data analytics solution designed to provide financial institutions with critical climate data, enabling them to offer SMEs the financing and knowledge essential for green transformation. By bridging the SME data gap, tilt reduces costs for financial institutions while supporting SMEs on their sustainability journey.

Our goal is to drive investment in climate mitigation and adaptation by equipping financial institutions with the insights needed to provide SMEs with targeted financing.

Watch [this video](https://youtu.be/5lTpwTqgj_0) to learn more about tilt. 

**What You’ll Find on This Website**

- **tilt’s Methodology:** Explore our approach through training videos. Our methodology links minimal data inputs from SMEs to climate data (e.g., climate scenarios, Life-Cycle-Assessment data), generating climate indicators that reveal a company's emission intensity and climate risks.
- **Research Data:** Access research data available for non-commercial use.
- **Climate Action Guide:** Discover our climate action guide, which standardizes the collection of revenue and climate action information from SMEs, improving data quality and enabling tailored sustainability loans.

These tools were developed under the CB-PASTAX program, funded by the EU. We've tested our product with three SMEs and five EU banks, with input from 21 banks in total. For applications beyond research, please visit www.tiltSMEs.org. Our prototype is launching with full-coverage in the Netherlands soon.

**We Value Your Feedback**

We strive for transparency and welcome input from financial institutions, researchers, and NGOs. Join the tilt community and share your [feedback here](https://docs.google.com/forms/d/1cwPCtlW3xP97aNIZ9Isge2zw5nJ-JnXvteckCO4oawo/viewform?edit_requested=true).

**Comment by maurolepore** [comment]
Closed by accident.

**Comment by maurolepore** [comment]
@AnneSchoenauer 

I implemented everything as in this [doc](https://docs.google.com/document/d/1dn29mtGD1fbtY1jIvLUVvZZX1KC3IHX7vNjpLEU20E8/edit) ([slack](https://2investinginitiative.slack.com/archives/C07BVEXP272/p1724178242773639)).

@Tilmon when you review that doc please highlight the changes (maybe use track changes or highlight them in a different color) so I can incorporate just those tweaks.

**Comment by Tilmon** [comment]
Hi @maurolepore please find the ticket with my review comments here 2DegreesInvesting/tiltWebTool/issues/213
