### ISSUE TITLE
Incorporate Tilman's suggestions into Webtool

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltWebTool#213]
Dear @maurolepore, 

responding to this [comment ](https://github.com/2DegreesInvesting/tiltWebTool/issues/203#issuecomment-2299969883), I reviewed the [Webtool Document](https://docs.google.com/document/d/1dn29mtGD1fbtY1jIvLUVvZZX1KC3IHX7vNjpLEU20E8/edit) and the actual [tool](https://tilt-staging-x6xfk2fceq-ey.a.run.app/). 

Based on the review, please do the following: 
**Webtool Document**
1. In the webtool document, I made suggestions in track changes. Can you please incorporate the changes? 

**Webtool** - general feedback sorted by tab

2. Welcoming Page:  Space between paragraphs seems larger for “Welcome to tilt’s Online Portal” card than for “What you’ll Find on This Website”. Is that true? If yes, can you please align the spacing? 
3. Dataset: When I logged in 20min ago, the data didn't load, I didn't even see the buffer "big data...". Now it worked again. Any idea what's the reason behind that? 
4. Dictionary: 2nd card was also empty when I logged in 20min ago, now it shows the actual dictionary. I guess this issue is somewhat related to the dataset not showing up (point 4). Just flagging here in case you have an idea what the reason might be. 
5. Method: This is just a heads up: We also need to upload a 2nd video once it's ready. Not sure yet when it will be ready, but ideally at some point next week. Just FYI.

**Comment by maurolepore** [comment]
WIP

- [ ] 1. 
- [ ] 2. 
- [ ] 3. 
- [ ] 4. 
- [ ] 5.

**Comment by maurolepore** [comment]
RE 2. I tested the app and confirm that after timeout the app looks gray, indicating the user that needs refresh. Refreshing results in logout. Loging back in brings the app back to life. 

The timeout now is 300s (5'). We can change the settings easily.

* https://github.com/2DegreesInvesting/tiltWebTool/issues/229

**Comment by maurolepore** [comment]
Having explained 3-4, I take that as understood. I'll close but feel free to open a dedicated issue if we need some change.

**Comment by Tilmon** [comment]
Hi @maurolepore , sorry for late response!

RE 1, 2 and 5: Great!

RE 3 & 4: thanks for explaining and already extending the time out period. I just tested it again and for some reason, the data don't load when logging in. I also re-freshed, logged in again but still no data are automatically previewed (see screenshot). When I click on the "Go!" button, the data load. But they don't show up without hitting the "Go!" button. Is that how it's supposed to be? 
Dicitionairy works fine now, so extending the time out period seems to have worked there!



![Image](https://github.com/user-attachments/assets/0eb738f1-24a2-4d19-9127-563de84e8f84)

**Comment by maurolepore** [comment]
@Tilmon you need to click on "Go".
It's easy to miss because the button is to light. This results from the tweaks we did to the theme, and a reason why I tend to prefer not tweaking themes -- I trust the theme-designers have a good reason for choosing the parameters they choose (colours, font-sized, etc.). It's a rabit whole that can easily suck more time that seems worth to me.

**Comment by Tilmon** [comment]
Hi @maurolepore OK I think then it's good :) I think I got confused because I was used to seeing data immediately from the past. But if a user looks at this the first time, I'm sure they'll figure out to click "Go!" ;)
