### ISSUE TITLE
Reduce cold start probability?

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltWebTool#244]
Hi @maurolepore , 

@AnneSchoenauer and I were wondering if it's possible to reduce the likelihood for a cold start somehow (that's how I understood one calls the case where the webtool looks like html text and not like the actual layout), e.g. by increasing computing power of the cloud? Is that something that's easy to fix by just upgrading our subscription?

**Comment by maurolepore** [comment]
@Tilmon and @AnneSchoenauer 

Yes, we can avoid cold-starts easily.


[We can avoid cold starts by always leaving 1 computer running but this will waste energy and money](https://github.com/2DegreesInvesting/tiltWebTool/issues/131#issuecomment-2307239320). 

Is that what you want?

**Comment by AnneSchoenauer** [comment]
Yes please ;) at least for the beginning! and could you please document on how to switch it back (at a later point)

**Comment by maurolepore** [comment]
Makes sense. I'll do it and record a video so you can undo it if it becomes too expensive.

**Comment by Tilmon** [comment]
@maurolepore please remember to add the video you already recorded!

**Comment by maurolepore** [comment]
* [Video](https://youtu.be/JN9MvUAEpMY)
* See also https://github.com/2DegreesInvesting/tiltWebTool/issues/229

**Comment by maurolepore** [comment]
FYI we're avoiding cold starts on the user-facing app but (to save costs) I'm still allowing the staging app to shut down when unused. This should give the users the best experience while keeping our cost relatively low.
