### ISSUE TITLE
Upload newest data release to webtool

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltWebTool#246]
Hi @maurolepore, 

can you please update the webtool data to the latest release that can be found [here](https://github.com/2DegreesInvesting/TiltDevProjectMGMT/issues/209#issuecomment-2307223733) in this ticket:

> Hi @Tilmon ,
> 
> I have uploaded the updated webtool data without the co2_footprint and co2e_avg columns in the [latest release](https://github.com/2DegreesInvesting/tiltOutput/releases/tag/v0.0.0.9006). The file name is webtool_output_v4_without_co2e.zip. Please close this issue after review! Thanks!

**Comment by maurolepore** [comment]
Do you expect any more changes to the data? 

Changing the data takes some effort and risk so I want to ensure we can fit your highest priorities in the very few days I have left.

**Comment by Tilmon** [comment]
Hi @maurolepore , no we don't expect anymore changes!
