### ISSUE TITLE
Embed webinar videos

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltWebTool#35]
Dear @maurolepore , 

it would be great if the webtool would also have the option to embed videos - e.g. if we record a webinar on our tool or so. But low priority for now :)

**Comment by maurolepore** [comment]
Thanks @Tilmon, 

It should be possible. The app's front end is simply html so we should be able to embed an iframe. Else we can always add a link.

**Comment by Tilmon** [comment]
Hi @maurolepore the video doesn't exist yet, unfortunately. We plan to record it in July. Once it's ready, we'll share it with you! 

cc' @AnneSchoenauer

**Comment by maurolepore** [comment]
OK, whenever you have it you can change the URL you see in this configuration file: [inst/config/video.yml](https://github.com/2DegreesInvesting/tiltWebTool/blob/main/inst/config/video.yml). That will result in a pull request that I can then approve and merge.

**Comment by Tilmon** [comment]
Hi @maurolepore , just as a heads up: We unfortunately won't be able to record the videos before my holiday anymore. We plan to do it on August 12th or 13th and will then share it with you!
cc @AnneSchoenauer

**Comment by maurolepore** [comment]
OK @Tilmon I moved this issue to that sprint.

We're already embedding one video as a place holder. Do we need a second one? What would be a good label for each of the two videos, e.g. "Webinar 1", and "Webinar 2"?

![image](https://github.com/user-attachments/assets/939424f2-1d3f-4442-941e-cfbcd2d25779)

**Comment by Tilmon** [comment]
Hi @maurolepore I wasn't aware of that. As discussed in today's sprint, I think the two videos can be shown on the same page, either next to or below each other, with their corresponding title. We don't know the exact titles yet, for now I think "Webinar 1" and "Webinar 2" works.

**Comment by AnneSchoenauer** [comment]
tilt online Training: https://youtu.be/WXNCYmXq7nw
tilt 3min intro presentation: https://youtu.be/5lTpwTqgj_0


Both links should be implemented already and pull requests are made.
