### ISSUE TITLE
Ask how "weight mode" should filter data

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWebTool#39]
This is potentially a bug since currently "weight mode" only excludes the two columns that don't belong the selected mode.

**Comment by maurolepore** [comment]
@Tilmon,

- [ ] ml01. can you please explain one more time what you expect to happen when the user chooses one of "equal_weight", "worst_case", or "best_case"?

Currently, selecting any of those values excludes columns that exactly match the other two values. 

For example, if a user picks "equal_weight", then the output lacks the columns "worst_case" and "best_case". It does not affect rows in any way.

,- [ ] ml02. Also, can you please confirm this only applies to the emissions indicator at product level, and not at emissions indicator at company level, neither at any level of the sector indicator? (for now I'm not only focusing on emissions and sector since transition risk is still unavailable).

**Comment by Tilmon** [comment]
Dear @maurolepore 

> ml01. can you please explain one more time what you expect to happen when the user chooses one of "equal_weight", "worst_case", or "best_case"? Currently, selecting any of those values excludes columns that exactly match the other two values.

That's correct I believe. On product-level the different weighting modes only affect the actual columns `equal_weight`, `best_case`, `worst_case`. @AnneSchoenauer do you agree? 

> ml02. Also, can you please confirm this only applies to the emissions indicator at product level, and not at emissions indicator at company level, neither at any level of the sector indicator? (for now I'm not only focusing on emissions and sector since transition risk is still unavailable).

The answer to ml01 only applies to the emission indicator on product level. On company-level for the emission indicator, the weighting choice also affects the column `emission_profile_share`, as a different weight on product-level affects also how many products on company-level are assigned to each emission_profile category. Does that make sense? 
The weighting choices are not available for sector and transition risk indicator yet, but @kalashsinghal will on this in this ticket [here ](https://github.com/orgs/2DegreesInvesting/projects/13/views/17?pane=issue&itemId=63752350) and [here](https://github.com/orgs/2DegreesInvesting/projects/13/views/17?pane=issue&itemId=63752649). 

Hope that clarifies your question. Let me know if it doesn't :)

**Comment by AnneSchoenauer** [comment]
@Tilmon 

ml01 is correctly answered. 

ml02 is not correct - the emission_profile_share is on company_level. At company_level we did not implement the mode yet. Only on product level. We are implementing now only for the transition_risk_score a differentiation between best_case, worst_case and equal_weight. 

@maurolepore I think for now you only need to take care of the mode on product_level and the mode will be implement as you can see in the toy data. It therefore refers only to different columns as you asked in ml01.

**Comment by maurolepore** [comment]
OK, I conclude the current behaviour is correct for the currently available data on the app. I removed the "bug" label.
