### ISSUE TITLE
Prune tilt* packages from DESCRIPTION

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWebTool#51]
E.g. remove the need to install tilt* packages on the server (i.e. exclude tilt* from Imports, Suggests, Remotes.

**Comment by AnneSchoenauer** [comment]
@maurolepore I am not quite sure if I understand this as we don't want anyone to install any code but just having the download option of our static data.

**Comment by maurolepore** [comment]
Done
