### ISSUE TITLE
Setup CI for tiltWebTool on tiltIndicatorAfter

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWebTool#70]
Ensure the app doesn't fall out of sync with the latest developments in tiltIndicatorAfter.

This isn't crucial while tiltWebTools is in rapid development because the frequency of change means that we would catch incompatible integration fairly soon. But in the mid-term it is important.

* Create a workflow that uses toy data, tiltIndicatorAfter, builds the app, deploys the app.

**Comment by AnneSchoenauer** [comment]
@Tilmon and @maurolepore  I think this is not needed as a task as we only present our data but it has nothing to do with running the tiltIndicatorAfter package right? So the app is just pictruing a static data set and not a constantly changing data set. Does this make sense?

**Comment by Tilmon** [comment]
@AnneSchoenauer makes sense to me!
