### ISSUE TITLE
Study registration and compare it with authentication

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWebTool#83]
In the last tech sprint we realized that we seem to require lower security than what an authentication service provides.

[Requirements](https://2investinginitiative.slack.com/archives/C04S69Z68P3/p1719332186105309?thread_ts=1719323729.848719&cid=C04S69Z68P3) (Anne/Tilman):

* Registration: A user registers with their name, latname, email, organization and agreement. The agreement is a checkbox that states something like "By registering the user agrees to 1) adhere to our terms-and-conditions, 2) use the data according to its license, 3) allow us to collect this private information. We store this data in e.g. a GoogleForm + GoogleSheet.

* Validation: The user provides a valid token that the systems sends via email.

* Access: The user can access the app and download the data.

# Comparing authentication versus registration

What's the conceptual and implementation difference between a service that requires users registration versus user authentication?

> User registration and user authentication serve distinct purposes in managing user access to a service. Registration involves collecting and validating user information to create a new account, often including steps like email verification and storing hashed passwords securely in a database. Authentication, on the other hand, is the process of verifying a user's identity using stored credentials, typically by comparing a provided password with the hashed version in the database, and managing user sessions upon successful login. 
> https://chatgpt.com/share/0f31f2c1-0759-453c-a6a7-d2337629fa84

### Authentication

The service providers (tilt) maintains a list of authorized users. Only those users can access the service (web tool). 

This gives us maximum control over who can access the service, but it costs us the effort in managing authorized users, and potentially the monetary cost of the authentication service (e.g. the standard plan of shinyapps.io).

### Registration

The users register themselves to the service (web tool). Any user can register, as long as they provide the minimum information we need from them (e.g. name, email, agree to use the data only for research).

This gives no control over who can access the service. I haven't researched this yet but it seems to cost us no effort or money. 

## Ideas

What might be the simplest way to implement access to a shiny app but only after the user registers and verifies their email?

I'd be happy to use something like GoogleForms and R packages to handle emails and tokens.

ChatGTP: https://chatgpt.com/share/d7f0bdf2-5956-46b9-9ed1-f7b22d1567b2

rOpenSci: The answer I got refer to authentication, not registration. It suggests approaches covered in https://github.com/2DegreesInvesting/tiltWebTool/issues/6

## Authentication and User Management in shinyapps.io

https://docs.posit.co/shinyapps.io/guide/authentication_and_user_management/

Summary (ChatGTP):

> To enable authentication on shinyapps.io (Standard and Professional plans), set the app's visibility to Private in the admin interface. Add authorized users by inviting them via email. Users authenticate using Google, GitHub, or shinyapps.io credentials. An authentication prompt appears for new visitors, requiring valid credentials. For logout, include a specific URL format in your app.

For detailed instructions, refer to the [shinyapps.io documentation](https://docs.posit.co/shinyapps.io).

**Comment by maurolepore** [comment]
* See #94

**Comment by AnneSchoenauer** [comment]
Dear @maurolepore, 

We were talking to Jakob last week and unfortunately we would need a password-secured App with a registration up-front. He had a very good idea: 

1. We will have a password for our R-Shiny (he said this is a normal function in R-Shiny)
2. We will then have a link on our normal tilt website [here](https://www.tiltsmes.org/) to a Google Form. In this Google Form people can fill in their name and orgnaisation and request the password. 
3. We will then send out the password with which the R-Shiny App is protected
4. People can then log-in to the App. 

Please note that we will still have on the App a Google Form link to request the data to download. 

Do you think this will work? If yes, I am happy to create such a Google Form and put it on our normal website once we are done with. I think for you the next step would be to make a password for our webtool.

**Comment by maurolepore** [comment]
Thanks @AnneSchoenauer, to follow up in a more focused issue I created 

* #134
