### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWebTool#86]
@AnneSchoenauer and @Tilmon 

It's currently unclear which license applies to the downloaded data. 

* [Here's is a page about licenses for non-software (e.g. data)](https://choosealicense.com/non-software/)
* For open source data, the best licenses seem to be the CC ones and [here is a tool to choose a CC license](https://chooser-beta.creativecommons.org/). 
* Note:
> You should only apply CC0 to your own work, unless you have the necessary rights to apply CC0 to another person’s work.
> --https://creativecommons.org/public-domain/cc0/
* [Learn more](https://creativecommons.org/licenses/)

### Examples

ForestGEO (my previous employer) hosts a similar ["tool" (website) to explore and request multiple datasets](https://www.forestgeo.si.edu/explore-data).

For example consider the [datasets from "Barro Colorado Island"](https://www.forestgeo.si.edu/explore-data/barro-colorado-island-termsconditionsrequest-forms). The "tool" (website) doesn't host the data. It simply links to terms and conditions and to a data-request form.

![image](https://github.com/2DegreesInvesting/tiltWebTool/assets/5856545/177b0b23-a343-447e-a823-9fafb83e9da2)

Data from this particular site (Barro Colorado Island) is pretty open -- similar to us. Note the message close to the top:

> The data is freely available for download [here](https://datadryad.org/stash/dataset/doi:10.15146/5xcp-0d46)

If you follow that link you'll land on a publication on [dryad](https://datadryad.org/stash), which is a great simple way to generate a persistent identifier for data. 

A similar service is [Zenodo, which is well integrated with GitHub releases.](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content)

----

### How about the licenses we use in our software?

The **software** in the backend of the app uses the same license as every other tilt packckage: [GPLv3](https://github.com/2DegreesInvesting/tiltWebTool/blob/7fa705d9ab47655bf4865eb44bcda6d7a794478c/DESCRIPTION#L8). But the users of the app see a front end which says nothing about how we expect them to use the data. 

The best licenses for software or data are typically different:

> All these licenses [e.g. GPLv3] are designed specifically to apply to source code [e.g. the tiltIndicator package], so if you’re releasing a package that primarily contains data, you should use a different type of license. -- https://r-pkgs.org/license.html#licenses-for-data

A license that is frequently used in open source data is CCO but it seems too liberal for what you want. A better one might be CCO-BY-NC-ND:

From https://www.openaccess.nl/en/creative-commons-licenses

> There are [six different CC license types](https://creativecommons.org/about/cclicenses/) and they all provide attribution and free access to your publication. The available ‘building blocks’ for a license are:

* BY – Credit must be given to the creator
* SA – Adaptations must be shared under the same terms
* NC – Only noncommercial uses of the work are permitted
* ND – No derivatives or adaptations of the work are permitted

--

https://creativecommons.org/licenses/by-nc-nd/4.0/

**Comment by AnneSchoenauer** [comment]
@Tilmon please see my email on this!

**Comment by AnneSchoenauer** [comment]
And as an add-on: I had another look for the library where to publish our data. And I think that Zenodo would be a very good fit as it says especially that it publishes also [data under EU programmes ](https://zenodo.org/communities/eu/curation-policy)- which is the case for us!

**Comment by AnneSchoenauer** [comment]
Dear @maurolepore, 

A quick update for you. 

After discussing with Jakob there will be most likely two ways on how people can access our data. The reason for that is that the webscraping of our data restricts ourselves to widely publish non-anonymised data that also contains web-scraped values. After discussing with Jakob we propose the following: 

<img width="327" alt="image" src="https://github.com/user-attachments/assets/60282a92-6ef4-41d5-80ef-5c8d4cfa4fa6">

We will check if this is possible with our lawyer and then let you know. 

All the best
Anne

**Comment by AnneSchoenauer** [comment]
shared with Jakob and waiting for final okay - but will be most likely the license that Mauro suggested. Therefore, closing this issue.
