### ISSUE TITLE
Develop a data dictionary in a collaborative GoogleSheet.

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWebTool#9]
[Demo_webtool](https://docs.google.com/presentation/d/1tfZKUxJgXxHAz3AOH4nej9whiqeUTeR2/edit#slide=id.p6) shows a data dictionary. 

I can create a template with all columns for each indicator. I'll need help defining them. 

- [ ] #11
- [ ] #12

**Comment by AnneSchoenauer** [comment]
I am assigining @Tilmon as he is responsible for the data dictionary.

**Comment by maurolepore** [comment]
Closing in favor of the more granular issues detailed in the task list at the top.
